[tasks.build_dev]
description = "Build wasm32-wasi binary"
install_crate = "cargo-wasi"
command = "cargo"
args = ["wasi", "build"]
watch = { ignore_pattern = "../target" }

[tasks.build_release]
description = "Build wasm32-wasi binary"
install_crate = "cargo-wasi"
command = "cargo"
args = ["wasi", "build", "--release"]
watch = { ignore_pattern = "../target" }

[tasks.format]
description = "Format Code with cargo-fmt"
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all"]
